### ISSUE TITLE
Hey I have a pull request to add phone verification can you give me access to push?

### ISSUE THREAD

**Issue by smconnor** [jamalo/php-ip-quality-score#3]
if you want happy to help further the project. Let me know! I have the diff ready

**Comment by jamalo** [comment]
@smconnor sounds great! You can fork the project and create a pull request. Let me know if that doesn't help.

**Comment by smconnor** [comment]
https://github.com/jamalo/php-ip-quality-score/pull/4

**Comment by jamalo** [comment]
@smconnor Thanks for the contribution.

**Comment by smconnor** [comment]
happy to help!

**Comment by smconnor** [comment]
not gonna make me contributor?

**Comment by jamalo** [comment]
Invited you as collaborator @smconnor

**Comment by smconnor** [comment]
thanks!
